name: deploy

kind: pipeline
type: docker

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: publish
  image: hexo:blogv1
  commands:
    - bash deploy.sh

trigger:
  branch:
    - master
