name: deploy

kind: pipeline
type: docker

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: publish
  image: hexo:blogv5
  volumes:
    - name: blog-env
      path: /opt/blog
      host:
        path: /mnt/dev/opt/hexo-blog
  environment:
    DEPLOY_CHECK_KEY:
      from_secret: DEPLOY_CHECK_KEY
  commands:
    - bash deploy.sh
    - bash deploy-website.sh

trigger:
  branch:
    - master
  event:
    - push
