name: deploy

kind: pipeline
type: docker

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive

- name: publish
  image: hexo:blogv2
  commands:
    - bash deploy.sh
    - bash deploy-website.sh

trigger:
  branch:
    - master
  event:
    - push
